name: vitarr
services:
#  radarr:
#    image: lscr.io/linuxserver/radarr:latest
#    container_name: radarr
#    environment:
#      - PUID=111
#      - PGID=321
#      - UMASK=002
#    volumes:
#      - /path/to/radarr/data:/config
#      - /path/to/movies:/movies #optional
#      - /path/to/download-client-downloads:/downloads #optional
#
#      - /path/to/config/sonarr:/config
#      - /host/data:/data
#    ports:
#      - 7878:7878
#    restart: unless-stopped
  influxdb2:
    image: influxdb:2-alpine
    container_name: influxdb2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: vitarr
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    restart:
      always
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    environment:
      GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana-admin-user
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana-admin-password
    secrets:
      - grafana-admin-user
      - grafana-admin-password
    volumes:
      - grafana-data:/var/lib/grafana
    restart:
      always

secrets:
  influxdb2-admin-username:
    file: ~/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ~/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ~/.env.influxdb2-admin-token
  grafana-admin-user:
    file: ~/.env.grafana-admin-user
  grafana-admin-password:
    file: ~/.env.grafana-admin-password
volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-data:

